apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dftfrontend.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "dftfrontend.labels" . | nindent 4 }}
data:
  configuration.properties: |-
    {{- .Values.configuration.properties | nindent 4 }}
