apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  annotations:
    avp.kubernetes.io/path: "dft/data/orchestrator-mysql"
    avp.kubernetes.io/secret-version: "5"
type: Opaque
stringData:
  dbUrl: <DB_URL>
  dbUser: <DB_USERNAME>
  dbPassword: <DB_PASSWORD>
